#![allow(clippy::new_without_default, clippy::manual_range_contains, clippy::redundant_closure)]
pub mod archive;
pub mod shell;
pub mod extract;
pub mod http;
pub mod wasm;
pub mod delay;
pub mod write_file;
pub mod discord;
pub mod slack;
pub mod github_dispatch;
pub mod git_sync;
