[package]
name = "anyhook-actions"
version = "0.0.3"
edition = "2024"

[dependencies]
anyhook-core = { path = "../anyhook-core" }
tokio = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
wasmtime = "47.0.2"
wasmtime-wasi = "47.0.2"
uuid = { workspace = true, features = ["v4"] }
cap-std = "4.0.2"
